namespace ReenbitTest.Core.DTOs
{
    /// <summary>
    /// Data transfer object representing a chat message with metadata
    /// </summary>
    /// <remarks>
    /// This DTO is used for transferring message data between client and server.
    /// It includes sentiment analysis results from Azure Cognitive Services and message status information.
    /// </remarks>
    public class MessageDto
    {
        /// <summary>
        /// Gets or sets the unique identifier for the message
        /// </summary>
        /// <value>
        /// An integer representing the message's primary key in the database
        /// </value>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the text content of the message
        /// </summary>
        /// <value>
        /// A non-null string containing the message body
        /// </value>
        public string Content { get; set; } = null!;

        /// <summary>
        /// Gets or sets the timestamp when the message was sent
        /// </summary>
        /// <value>
        /// A DateTime in UTC format representing when the message was created
        /// </value>
        public DateTime SentAt { get; set; }

        /// <summary>
        /// Gets or sets the username of the message sender
        /// </summary>
        /// <value>
        /// A non-null string containing the sender's username
        /// </value>
        public string SenderUserName { get; set; } = null!;

        /// <summary>
        /// Gets or sets the full name of the message sender
        /// </summary>
        /// <value>
        /// A non-null string containing the sender's full name (first name + last name)
        /// </value>
        public string SenderFullName { get; set; } = null!;

        /// <summary>
        /// Gets or sets the identifier of the chat room this message belongs to
        /// </summary>
        /// <value>
        /// An integer representing the chat room's primary key
        /// </value>
        public int ChatRoomId { get; set; }

        /// <summary>
        /// Gets or sets the sentiment label from Azure Text Analytics
        /// </summary>
        /// <value>
        /// A string containing the sentiment classification (positive, neutral, negative, or mixed),
        /// or null if sentiment analysis was not performed
        /// </value>
        /// <remarks>
        /// This value is generated by Azure Cognitive Services Text Analytics API.
        /// The sentiment is determined using natural language processing and
        /// provides contextual understanding of message tone.
        /// </remarks>
        public string? SentimentLabel { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the message has been read by the recipient
        /// </summary>
        /// <value>
        /// <c>true</c> if the message has been read; otherwise, <c>false</c>
        /// </value>
        /// <remarks>
        /// This property is user-specific when queried through appropriate endpoints.
        /// </remarks>
        public bool IsRead { get; set; } = false;
    }
}